### ISSUE TITLE
Grand Staff issue

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#542]
I've found that some songs for piano 4 hands, will cause an issue with the grand staffs, for instance this song:

X:1
T:Ett barn är fött
T:Vi har kul i jul
C:arr: Camilla Liedbergius
%%score { 1 | 2 } { ( 3 5 ) | 4 }
L:1/8
Q:1/4=90
M:4/4
I:linebreak $
K:G
V:1 treble nm="Primo"
V:2 treble 
V:3 bass nm="Secundo"
V:4 bass 
V:5 bass 
V:1
 D2 | G2 G2 A2 A2 | B2 B2 d3 c | B2 cB A2 BA | %4
 G6 D2 | G2 G2 A2 A2 | B2 B2 d3 c | B2 cB A2 BA | %8
 G6 G2 | d2 d2 e2 e2 | A2 Bc B2 Bc | d2 d2 e2 e2 | %12
 A6 D2 | G2 G2 A2 A2 | B2 B2 d3 c | B2 cB A2 BA | %16
 G6 |] %17
V:2
 z2 | B,2 B,2 D2 D2 | G2 G2 A4 | D4 C4 | %4
 B,2 C2 B,2 z2 | B,2 D2 E2 D2 | D4 E4 | D4 C4 | %8
 B,6 z2 | G4 C4 | D4 G4 | D2 B,2 E4 | %12
 A6 z2 | B,2 D2 E2 D2 | G8 | G4 F4 | %16
 D6 |] %17
V:3
 z2 | [G,B,,]2 D,2 [F,C,]2 D,2 | [G,B,,]2 D,2 [A,C,]2 F,2 | G,4 F,4 | %4
 G,2 A,2 G,2 z2 | [G,B,,]2 [G,D,]2 [G,E,]2 F,2 | G,4 ^G,2 A,2 | =G,4 F,4 | %8
 G,6 z2 | [G,D,]4 [G,E,]4 | F,4 [G,D,]4 | [A,D,]4 ^G,2 B,2 | %12
 A,6 z2 | G,4 G,2 E,2 | D4 B,2 C2 | D4 C4 | %16
 B,6 |] %17
V:4
 z2 | G,,4 D,,4 | G,,8 | G,,4 D,4 | %4
 G,,6 z2 | G,,2 B,,2 C,2 D,2 | G,,4 E,,2 A,,2 | D,8 | %8
 z2 D,2 G,,2 z2 | B,,4 C,4 | D,2 C,2 B,,4 | F,,4 E,,2 ^G,,2 | %12
 A,,2 B,,2 ^C,2 z2 | G,,2 B,,2 =C,2 D,2 | G,2 F,2 =F,2 E,2 | D,8 | %16
 G,,6 |] %17
V:5
 x2 | x8 | x8 | x8 | %4
 x8 | x8 | x8 | x8 | %8
 x8 | x8 | x8 | x4 D,4 | %12
 ^C,2 D,2 E,2 z2 | x8 | x8 | x8 | %16
 x6 |] %17

will make the staff names look like this:

![Skärmavbild 2020-10-29 kl  21 49 21](https://user-images.githubusercontent.com/18282700/97631225-ece33e00-1a30-11eb-97d6-7aefb0d18845.png)

I think it has to do with the 2 voices in Secundo right hand.

This when using the "Synth Editor" version of beta 13 => beta 20
It is also not playing back in beta 18, 19 and 20, but it is playing back in beta 13 => 17

**Comment by musikboden** [comment]
Another example, now with 6 voices, I think it is the many voices that mess it up

X:1
T:Nu tändas tusen juleljus
T:Vi har kul i jul
C:arr: Camilla Liedbergius
%%score { 1 | 2 } { ( 3 5 ) | ( 4 6 ) }
L:1/8
Q:1/4=90
M:4/4
I:linebreak $
K:D
V:1 treble nm="Primo"
V:2 treble 
V:3 treble nm="Secundo"
V:4 bass 
V:5 treble 
V:6 bass 
V:1
 z2 | z8 | z4 z2 || A2 | %4
 f2 f2 e2 e2 | d2 B2 A3 A | B2 B2 e2 c2 | A6 A2 | %8
 a2 a2 g2 g2 | f2 d2 B3 B | c2 c2 e2 e2 | d6 A2 | %12
 f2 f2 e2 e2 | d2 B2 A3 A | B2 B2 e2 c2 | A6 A2 | %16
 a2 a2 g2 g2 | f2 d2 B3 B | c2 c2 e2 e2 | d6 |] %20
V:2
 z2 | z8 | z4 z2 || z2 | %4
 A4 G4 | F2 G2 F4 | G8 | F6 z2 | %8
 F2 A2 B2 c2 | A4 ^G4 | =G8 | F6 z2 | %12
 A4 G4 | F2 G2 F4 | G8 | F6 z2 | %16
 F2 A2 B2 c2 | A4 ^G4 | =G8 | F6 |] %20
V:3
 B,2 | C2 C2 E2 E2 | D6 ||[K:bass] z2 | %4
 ([A,F,]2 D2) ([A,G,]2 C2) | [DF,]4 ([A,D,]2 D2) | ([B,D,]2 [DG,]2) (C2 E2) | [DF,]6 z2 | %8
 [DA,]4 ([DB,]2 [CA,]2) | [DA,]4 [D^G,]4 | C8 | [DF,]6 z2 | %12
 ([A,F,]2 D2) ([A,G,]2 C2) | [DF,]4 ([A,D,]2 D2) | ([B,D,]2 [DG,]2) (C2 E2) | [DF,]6 z2 | %16
 [DA,]4 ([DB,]2 [CA,]2) | [DA,]4 [D^G,]4 | C8 | [DF,]6 |] %20
V:4
 z2 | z4 G,4 | (F,2 G,2 F,2) || z2 | %4
 D,4 A,,4 | D,4 F,,4 | G,,2 B,,2 A,,4 | D,2 A,,2 D,,2 z2 | %8
 F,,4 G,,2 A,,2 | D,2 B,,2 E,,4 | A,,8 | [A,,D,,]6 z2 | %12
 D,4 A,,4 | D,4 F,,4 | G,,2 B,,2 A,,4 | D,2 A,,2 D,,2 z2 | %16
 F,,4 G,,2 A,,2 | D,2 B,,2 E,,4 | A,,8 | [A,,D,,]6 |] %20
V:5
 x2 | A,4 A,4 | (A,2 B,2 A,2) ||[K:bass] z2 | %4
 x8 | x8 | x4 G,4 | z8 | %8
 z8 | z8 | A,4 =G,4 | x8 | %12
 x8 | x8 | x4 G,4 | z8 | %16
 z8 | z8 | A,4 =G,4 | x6 |] %20
V:6
 x2 | A,,8 | D,6 || x2 | %4
 x8 | x8 | x8 | x8 | %8
 x8 | x8 | x8 | x8 | %12
 x8 | x8 | x8 | x8 | %16
 x8 | x8 | x8 | x6 |] %20

![Skärmavbild 2020-10-29 kl  22 25 18](https://user-images.githubusercontent.com/18282700/97634303-c247b400-1a35-11eb-8b8e-334aaed318c9.png)

Notice the bass clef in secundo right hand, bar 4, after the line break it jumps right back to treble clef,  it is supposed to stay in bass clef...

![Skärmavbild 2020-10-29 kl  22 21 45](https://user-images.githubusercontent.com/18282700/97633919-274eda00-1a35-11eb-9c87-852da858ec0b.png)

Here it's really a mess, in secundo right hand, bar 2 & 3, the clef is treble and the highest voice is displayed as if it was written in bass clef... 😱

**Comment by paulrosen** [comment]
Yeah, can confirm. I'll probably get this in the next beta.

**Comment by musikboden** [comment]
👍

**Comment by paulrosen** [comment]
Will be in beta 21.

**Comment by musikboden** [comment]
Paul, will you try to solve the other issue as well? This one:

Here it's really a mess, in secundo right hand, bar 2 & 3, the clef is treble and the highest voice is displayed as if it was written in bass clef... 😱

Using beta 13 => 20, Editor Synth and Chrome Version 86.0.4240.111 (Officiell version) (x86_64)

**Comment by paulrosen** [comment]
Here's a simplified version:
```
X:1
T:notes-placed-as-if-bass-clef
%%score (3 5) 
L:1/4
V:3
C4 ||[K:bass]
V:5
A,4 ||[K:bass]
```
It is happening because of the switch to bass clef. The other voice is staying in bass clef. A workaround is:
```
X:1
T:notes-placed-as-if-bass-clef
%%score (3 5) 
L:1/4
V:3
C4 ||[K:bass]
V:5
[K:treble]A,4 ||[K:bass]
```
I'll see if I can fix it, but that should get passed this.

**Comment by paulrosen** [comment]
The first part is fixed in beta.21. The second part (about the bass clef) is on my list as a separate issue.

**Comment by musikboden** [comment]
Hi Paul! The Staff names is working now, in the examples above 👍

However they don't play back using "editor-synth" beta 21, that was the second issue in this thread.
I tried by also removing the "8va" decorations but still no luck

**Comment by musikboden** [comment]
Hi again, they don't playback because of the double T:s I noticed, and you already found what's causing it, sorry about that 🙄
