### ISSUE TITLE
Lost sound

### ISSUE THREAD

**Issue by nbruley** [paulrosen/abcjs#764]
Various people running iOS have told me that the sound on my website and within my mobile application does not play after leaving to do something else and then returning to the app or website. They have to close the app or refresh the website in order to get the sound to play again. It does not appear to be an issue for Android users. Any idea what might be happening there?

**Comment by paulrosen** [comment]
Which version are you using? I just fixed a problem with iOS so try beta 39.

But - there might still be weird things on iOS when a call comes in or something else that interrupts. I think stopping (or pausing) and restarting the sound should help.

**Comment by nbruley** [comment]
My tester says it is very much improved, though not 100% fixed. Thanks!!

**Comment by nbruley** [comment]
Update: Tester now says that he was mistaken. I think he was testing on Safari (which works well) but not in Chrome (as he had done before). 

Process to reproduce the issue:
Open the app in Chrome.  
Play a tune.
Leave the app open and switch to GMail.
Open a mail and type a couple of sentences.  Leave it open.
Return to Chrome.  App will still be the way you left it.
Try to play your tune. 
Fails to play every time until you close the browser tab and reopen.

I cannot reproduce the problem, though I also have iOS 15 and Chrome. However, one or two others have complained about the same issue when in the app.

**Comment by paulrosen** [comment]
That is odd - there is only one browser in iOS. The one with Chrome branding is really Safari. 

I'll see if I can reproduce it on an iphone. When you say "go to gmail" you mean an app on the iphone? I don't have that but I'll try another app.

**Comment by samuelbradshaw** [comment]
Sometimes browsers pause things that are happening in a tab when that tab is put in the background. I think ABCJS uses requestAnimationFrame(). See https://developers.google.com/web/updates/2017/03/background_tabs#requestanimationframe

**Comment by paulrosen** [comment]
It does use requestAnimationFrame for the cursor but the sound is completely constructed before playing and is the WebAudio interface.

**Comment by paulrosen** [comment]
Another clarification - the tester had played the tune all the way through and it was quiet before switching to gmail, right?

**Comment by nbruley** [comment]
Sounds like any app will do it, e.g. weather app. Anything that changes what iOS is actively working on.
If all he does is refresh the page, move away, and come back, it plays. If he plays a few seconds before moving to a new app and comes back, it doesn't play (consistently).

**Comment by AlfredCorduan** [comment]
Again, can I be sure I have the right build?

**Comment by nbruley** [comment]
FYI, I set a variable within the ABCJS file and we confirmed he is seeing abcjs_basic v6.0.0-beta.39.

**Comment by nbruley** [comment]
One other comment. Tester says Safari on iPad works fine (only failed once). But Safari on his iPhone fails the same as in Chrome. So both of his iDevices have the same issue. Audio returns after page refresh. Pretty strange.
Do I need to do some sort of audio cleanup when they press stop or start to reset some sort of memory setting?

**Comment by paulrosen** [comment]
For the version, you can do `console.log(ABCJS.signature)`.

I opened https://paulrosen.github.io/abcjs/examples/basic-synth.html and started it playing.

Then I went back to the home screen and it cut off playing.

Then I opened it again and it was still on the state that has the button that says "stop audio".

I tapped that button and it switched back to "Activate audio" and clicked it again and it started playing.

I tried a few things in between and couldn't get it to fail. I even opened a copy if the site in both chrome and safari and went between them and it still came back ok.

Can you try to duplicate using that site and give me steps to reproduce?

**Comment by nbruley** [comment]
So this is interesting. He does not have the same issue in your sample page, so there must be a programming difference that is affecting the playback. He can stop your playback, move away, then come back and press play again and it plays, unlike how it works on my page. I added alerts when I create the buffer and when I stop the buffer, and it only happens once each time, with the same variable, so I'm not sure what I am missing.

Creating the buffer:
```
var visualObj = ABCJS.renderAbc("*", TuneABC, abcOptions)[0]; //create object to play but don't display ("*")
createSynth = new ABCJS.synth.CreateSynth();	 // This does a bare minimum so this object could be created in advance, or whenever convenient.
```

stopping:
```
if (createSynth) { // abcjs player
	createSynth.stop();
	timer.stop();
}

```

I do have code to check when it reaches the end of the song to change the play button when it reaches the end, but it doesn't matter whether he stops or lets it play to the end anyway.

**Comment by AlfredCorduan** [comment]
How and when are the sound fonts loaded?

**Comment by AlfredCorduan** [comment]
I am forced to hit "Stop" to replay the sample page, even if I completed
the tune.  Something different about the reset coming from the button
event?   Ours takes action upon completion of the play to reset the button
automatically.

**Comment by nbruley** [comment]
Per our conversation, tester got all three alerts when the audio didn't play, so it is getting to the createSynth command (Alfred, that's where the call to sound font is located.)  Everything appears to be playing as normal, just no sound.

```
alert('1');
if (ABCJS.synth.supportsAudio()) {
	alert('2');
	audioContext.resume().then(function () {  // In theory the AC shouldn't start suspended because it is being initialized in a click handler, but iOS seems to anyway.
		// createSynth.init preloads and caches all the notes needed. There may be significant network traffic here.
		alert('3');
		return createSynth.init({
			visualObj: visualObj,
			audioContext: audioContext,
			options: {
				chordsOff: true,
				soundFontUrl: "soundfont/FluidR3-GM/",
				soundFontVolumeMultiplier: .8,
				midiTranspose: transposeAmount,
				millisecondsPerMeasure: visualObj.millisecondsPerMeasure(),
				program: musicProgramNumber //https://soundprogramming.net/file-formats/general-midi-instrument-list/ subtract 1  | https://github.com/paulrosen/midi-js-soundfonts/tree/gh-pages/FluidR3_GM
				//pan: [ -0.3, -0.1, 0.1, 0.3, 0 ],
			}
		}).then(function (response) {
			// console.log(response); // this contains the list of notes that were loaded.
			// createSynth.prime actually builds the output buffer.
			return createSynth.prime();
		}).then(function () {
			// At this point, everything slow has happened. createSynth.start will return very quickly and will start playing very quickly without lag.
			createSynth.start();
			timer.start();
			return Promise.resolve();
		}).catch(function (error) {
			if (error.status === "NotSupported") {
				alertOK(translate("Audio not supported","text"),translate("OK","text"));
			} else
				console.warn("synth error", error);
		});
	});
} else {
	alertOK(translate("Audio not supported","text"),translate("OK","text"));
};
} //end play with abcjs
```

**Comment by nbruley** [comment]
I just realized I'm on iOS 14 not 15 like I thought. I'm tempted to upgrade to see if that changes anything.

Tester confirmed that even though he doesn't hear sound, the song "plays" to the end and then the play icon changes back to a play button at the end of the song as if ready to play again. So the programming works, just no sound.

**Comment by nbruley** [comment]
And the mystery only deepens, because tester just stated that the same loss of sound happens for the musical library, https://github.com/PencilCode/musical.js, so this isn't limited to just this library.  (implemented for testing here, https://gospelriver.com/play_abc/). It doesn't use mp3 files, just synthesized sound.

**Comment by nbruley** [comment]
So I've reproduced the example on my server, using my server's soundfont and server resources.
https://gospelriver.com/favtest/basic-synth.html
Tester says this works for him. So my next planned step is to change the programming to recognize end of song like I do on my app and see if that breaks it.

**Comment by nbruley** [comment]
It appears that I've found the solution to the problem. When comparing code I noticed the statement:
An audio context is needed - this can be passed in for two reasons:
1) So that you can share this audio context with other elements on your page.
2) So that you can create it during a user interaction so that the browser doesn't block the sound.
When I initialized the audioContext within the synth.supportsAudio() statement, the tester said that the sound functioned normally. I had left it outside thinking that when I was (previously) playing from multiple functions, I would want a way to clear any previous instances, but that probably wouldn't have been true anyway if each instance is local and not global.  At any rate, I'm hoping this is resolved, will do more testing.

**Comment by paulrosen** [comment]
I hope that works for you. Each version of Safari introduces new problems. I did figure out that keeping an AudioContext is important. Grabbing a number of AudioContexts in one tab can actually make another tab fail. (At least Chrome used to work that way.)

**Comment by paulrosen** [comment]
I'll reopen this if your testing turns up anything.

**Comment by AlfredCorduan** [comment]
So far so good, whatever you and Nathan worked out.  Massive win.  The
symptom has shown  up in other apps [TuneBooks, which I use to create and
edit .abc], albeit infrequently (this one was completely reproducible).
The "Musical" JavaScript abc library which we were using before we figured
your awesome capabilities out is still showing the symptom.  We now use it
only for testing, sanity checking - so is not being pursued.

Thanks, BTW, for all you do.  You have revolutionized our hymnal app which
is being used all over the world.  We were stuck on .mp3, and then working
with Musical.  So far we have published some 850 melodies, scores and
playback, with another 500 or so waiting in the wings.

**Comment by nbruley** [comment]
Per https://github.com/paulrosen/abcjs/issues/774 , using multiple audioContexts prevents the repeat feature from working, e.g. 
```
timer = new ABCJS.TimingCallbacks(visualObj, {
						beatCallback: function(beatNumber, totalBeats, totalTime) {
```
We have noticed that running this before leaving the tab seems to enable the sound to play again when coming back though:
```
if (createSynth) { // abcjs player
createSynth.stop();
timer.stop();
}
```
I want them to be able to click around while the music is playing, so I don't want to run this on an onclick event.
